[package]
name = "play"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rayon = "1.11.0"
thiserror = "2.0.16"
tokio = {version = "1.47.1", features = ["rt", "macros","rt-multi-thread","time"]}
