[package]
name = "parallel_task"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"

[dev-dependencies]
rand = "0.9.2"
rayon = "1.11.0"
tokio = {version = "1.4.3", features = ["time"]}
